layout_spectrum: 0.1856134
typography_spectrum: 0.1326165
color:
  saturation: 0.7078853
  brandStrength: 0.363504
  lightness: 0.1344086
  rhythmicContrast: 0.4964158
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: iClickMedia
title: Design Communication
